export const NVIDIA_MODELS = [
  {
    id: "qwen-image-edit-nvpcb-ovsl2sl",
    name: "qwen-image-edit-nvpcb-ovsl2sl",
    displayName: "Qwen Image Edit (NV-PCB OVSL2SL)",
    vendor: "NVIDIA",
    vendorLogo: "nvidia",
    type: "Image Editing",
    category: "Synthetic Data & Industrial",
    description: "An image edit model specialized for Omniverse synthetic to photographic solder-light style captured at NVIDIA PCB inspection stations.",
    badge: "Downloadable",
    timeAgo: "1mo",
    likes: "+4",
    requiresSourceImage: true,
    supportedRatios: ["1:1", "16:9", "4:3"],
    defaultSteps: 30,
    tags: ["Synthetic Data Generation", "Omniverse", "PCB Inspection", "Style Transfer"],
    endpointId: "nvidia/qwen-image-edit-nvpcb-ovsl2sl"
  },
  {
    id: "qwen-image",
    name: "qwen-image",
    displayName: "Qwen-Image",
    vendor: "Qwen",
    vendorLogo: "qwen",
    type: "Text-to-Image",
    category: "Foundation Model",
    description: "Qwen-Image is a text-to-image foundation model with advanced multilingual text rendering.",
    badge: "Downloadable",
    timeAgo: "3mo",
    likes: "+5",
    requiresSourceImage: false,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultSteps: 25,
    tags: ["Multilingual Text", "Together AI", "High Fidelity", "Typography"],
    endpointId: "qwen/qwen-image"
  },
  {
    id: "qwen-image-edit",
    name: "qwen-image-edit",
    displayName: "Qwen-Image-Edit",
    vendor: "Qwen",
    vendorLogo: "qwen",
    type: "Image Editing",
    category: "Subject Consistency",
    description: "Qwen-Image-Edit is an image editing model with multilingual text editing and strong subject consistency.",
    badge: "Downloadable",
    timeAgo: "3mo",
    likes: "+3",
    requiresSourceImage: true,
    supportedRatios: ["1:1", "16:9", "4:3"],
    defaultSteps: 30,
    tags: ["Text Editing", "Subject Consistency", "In-Context Edit"],
    endpointId: "qwen/qwen-image-edit"
  },
  {
    id: "flux.2-klein-4b",
    name: "flux.2-klein-4b",
    displayName: "FLUX.2-klein-4B",
    vendor: "Black Forest Labs",
    vendorLogo: "bfl",
    type: "Text-to-Image / Editing",
    category: "Ultra Fast Distilled",
    description: "FLUX.2-klein-4B is a distilled image generation and editing model, producing outputs at lightning speed.",
    badge: "Downloadable",
    timeAgo: "4mo",
    likes: "+8",
    usageCount: "338K",
    requiresSourceImage: false,
    allowSourceImage: true,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultSteps: 8,
    tags: ["Distilled", "Ultra Fast", "High Efficiency", "Black Forest Labs"],
    endpointId: "black-forest-labs/flux.2-klein-4b"
  },
  {
    id: "stable-diffusion-3.5-large",
    name: "stable-diffusion-3.5-large",
    displayName: "Stable Diffusion 3.5 Large",
    vendor: "Stability AI",
    vendorLogo: "stability",
    type: "Text-to-Image",
    category: "High Resolution Foundation",
    description: "Stable Diffusion 3.5 is a popular text-to-image generation model with superior prompt adherence and image clarity.",
    badge: "Downloadable",
    timeAgo: "1y",
    likes: "+3",
    requiresSourceImage: false,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9"],
    defaultSteps: 40,
    tags: ["Stability AI", "High Adherence", "Photorealistic", "SD 3.5"],
    endpointId: "stabilityai/stable-diffusion-3.5-large"
  },
  {
    id: "FLUX.1-Kontext-dev",
    name: "FLUX.1-Kontext-dev",
    displayName: "FLUX.1 Kontext Dev",
    vendor: "Black Forest Labs",
    vendorLogo: "bfl",
    type: "Multimodal / Image Edit",
    category: "In-Context Generation",
    description: "FLUX.1 Kontext is a multimodal model that enables in-context image generation and editing.",
    badge: "Downloadable",
    timeAgo: "1y",
    likes: "+4",
    usageCount: "7K",
    requiresSourceImage: false,
    allowSourceImage: true,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultSteps: 28,
    tags: ["Multimodal", "In-Context", "Prompt Matching", "Editing"],
    endpointId: "black-forest-labs/flux.1-kontext-dev"
  },
  {
    id: "FLUX.1-schnell",
    name: "FLUX.1-schnell",
    displayName: "FLUX.1 Schnell",
    vendor: "Black Forest Labs",
    vendorLogo: "bfl",
    type: "Text-to-Image",
    category: "High Speed Generation",
    description: "FLUX.1-schnell is a distilled image generation model, producing high quality images at fast speeds.",
    badge: "Downloadable",
    timeAgo: "1y",
    likes: "+7",
    usageCount: "227K",
    requiresSourceImage: false,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultSteps: 4,
    tags: ["Schnell", "Real-Time", "Distilled", "Speed Monster"],
    endpointId: "black-forest-labs/flux.1-schnell"
  },
  {
    id: "FLUX.1-dev",
    name: "FLUX.1-dev",
    displayName: "FLUX.1 Dev",
    vendor: "Black Forest Labs",
    vendorLogo: "bfl",
    type: "Text-to-Image",
    category: "State of the Art Quality",
    description: "FLUX.1 is a state-of-the-art suite of image generation models with exceptional detail rendering.",
    badge: "Downloadable",
    timeAgo: "1y",
    likes: "+12",
    requiresSourceImage: false,
    supportedRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultSteps: 28,
    tags: ["FLUX.1", "State of the Art", "Photorealistic", "Detail Master"],
    endpointId: "black-forest-labs/flux.1-dev"
  }
];

export const ASPECT_RATIOS = [
  { label: "1:1", value: "1:1", width: 1024, height: 1024, icon: "square" },
  { label: "16:9", value: "16:9", width: 1280, height: 720, icon: "wide" },
  { label: "9:16", value: "9:16", width: 720, height: 1280, icon: "tall" },
  { label: "4:3", value: "4:3", width: 1024, height: 768, icon: "standard" },
  { label: "3:4", value: "3:4", width: 768, height: 1024, icon: "portrait" },
  { label: "21:9", value: "21:9", width: 1344, height: 576, icon: "cinematic" }
];

export const SAMPLE_PROMPTS = [
  "A futuristic NVIDIA AI microchip glowing with green neon circuitry, hyper-detailed render, 8k resolution, cinematic lighting",
  "Cyberpunk cityscape at night with wet reflective streets, neon signs in kanji, volumetric fog, octane render",
  "Close-up electronic circuit board inspection, PCB solder points macro photography, industrial quality",
  "A majestic mechanical eagle made of polished gold and chrome, perched on a crystal peak, dramatic sunset background",
  "Minimalist studio product shot of a sleek futuristic glass sphere with swirling green liquid inside, white studio backdrop",
  "Photorealistic portrait of a female astronaut gazing out a spaceship window at a nebula, intricate helmet detail"
];
